import type { Metadata } from "next";
import "../globals.css";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@libraries/i18n/routing";
import RootProvider from "@providers/root-provider";
import "@/_styles/main.scss";

interface IRootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export const metadata: Metadata = {
  title: "Next Jira Core Web",
  description: "Generated by Next Jira Core Web",
};

export default async function RootLayout({
  children,
  params,
}: IRootLayoutProps) {
  const { locale } = await params;

  // 유효하지 않은 locale 체크
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // 서버 사이드에서 번역 메시지 로드
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <RootProvider locale={locale} messages={messages}>
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
